---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./ingress-nginx.yaml
  - ./istio.yaml
  - ./jaegertracing.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./opentelemetry-operator.yaml
  - ./prose.yaml
  - ./weave-gitops.yaml
