---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prose-system-opentelemetry-operator-crds
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-1/apps/prose-system/opentelemetry-operator/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: opentelemetry-operator
      namespace: prose-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prose-system-opentelemetry-operator-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-prose-system-opentelemetry-operator-crds
  path: ./kubernetes/cluster-1/apps/prose-system/opentelemetry-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
