---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prose-system
resources:
  - ./prose-deployment.yaml
  - ./prose-service.yaml
  - ./presidio-deployment.yaml
  - ./presidio-service.yaml
  - ./ingress.yaml