---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  #- jaeger/ks.yaml
  #- ./opa-envoy-plugin/ks.yaml
  #- ./opentelemetry-operator/ks.yaml
  - ./prose/ks.yaml
