---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prose-system
resources:
  - helmrelease.yaml
  - ingress.yaml
  # - https://github.com/jaegertracing/jaeger-operator/releases/download/v1.46.0/jaeger-operator.yaml
