---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ./example-lua-filter.yaml
  #- ./opa-envoy-filter.yaml
  - ./tap-filter.yaml
  - ./tracing.yaml
